# TFLint integration tests for tf2 rules

load("@bazel_skylib//lib:unittest.bzl", "unittest")
load(":tflint_integration_test.bzl", "tflint_integration_test_suite")

tflint_integration_test_suite(name = "tflint_integration_tests")