# Build file for runner scripts

package(default_visibility = ["//tf2/private:__subpackages__"])

exports_files([
    "terraform_runner.sh",
    "terraform_init.sh",
    "copy_module_files.sh",
    "copy_source_files.sh",
    "terraform_wrapper.sh",
])