// Package terraform provides a Gazelle language extension for Terraform modules.
package terraform

import (
	"flag"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"sync"

	"github.com/bazelbuild/bazel-gazelle/config"
	"github.com/bazelbuild/bazel-gazelle/label"
	"github.com/bazelbuild/bazel-gazelle/language"
	"github.com/bazelbuild/bazel-gazelle/repo"
	"github.com/bazelbuild/bazel-gazelle/resolve"
	"github.com/bazelbuild/bazel-gazelle/rule"
)

const (
	terraformName     = "terraform"
	tfModuleKind      = "tf_module"
	tfStackKind       = "tf_stack"
	tfTestKind        = "tf_test"
	defaultModuleName = "tf_module" // Default name for tf_module rules
	defaultStackName  = "tf_stack"  // Default name for tf_stack rules
	defaultTestName   = "tf_test"   // Default name for tf_test rules
)

// NewLanguage creates a new Gazelle language extension for Terraform.
func NewLanguage() language.Language {
	return &terraformLang{}
}

type terraformLang struct {
	// moduleName is the bzlmod module name parsed from MODULE.bazel
	// Used to generate correct load statements like @module_name//tf2:def.bzl
	moduleName     string
	moduleNameOnce sync.Once
	repoRoot       string
}

// terraformConfig holds configuration for the terraform extension.
type terraformConfig struct {
	enabled         bool
	providerMapping map[string]string // Maps provider names to registry labels
}

func newTerraformConfig() *terraformConfig {
	return &terraformConfig{
		enabled:         true,
		providerMapping: make(map[string]string),
	}
}

// parseModuleNameFromFile extracts the module name from a MODULE.bazel file.
// Returns empty string if the file doesn't exist or can't be parsed.
func parseModuleNameFromFile(path string) string {
	content, err := os.ReadFile(path)
	if err != nil {
		return ""
	}

	// Look for: module(name = "module_name", ...)
	// Simple regex to extract the name attribute
	moduleRegex := regexp.MustCompile(`module\s*\(\s*name\s*=\s*"([^"]+)"`)
	matches := moduleRegex.FindStringSubmatch(string(content))
	if len(matches) >= 2 {
		return matches[1]
	}

	return ""
}

// getModuleName returns the bzlmod module name, parsing MODULE.bazel if needed.
func (l *terraformLang) getModuleName() string {
	l.moduleNameOnce.Do(func() {
		if l.repoRoot != "" {
			modulePath := filepath.Join(l.repoRoot, "MODULE.bazel")
			l.moduleName = parseModuleNameFromFile(modulePath)
		}
		// Fallback to rules_tf2 if we couldn't parse the module name
		if l.moduleName == "" {
			l.moduleName = "rules_tf2"
		}
	})
	return l.moduleName
}

// Name returns the name of the language.
func (l *terraformLang) Name() string { return terraformName }

// Kinds returns the kinds of rules generated by this language.
func (l *terraformLang) Kinds() map[string]rule.KindInfo {
	return map[string]rule.KindInfo{
		tfModuleKind: {
			MatchAny:        false,
			NonEmptyAttrs:   map[string]bool{"srcs": true, "providers": true},
			SubstituteAttrs: map[string]bool{},
			MergeableAttrs:  map[string]bool{"srcs": true, "providers": true},
			ResolveAttrs:    map[string]bool{},
		},
		tfStackKind: {
			MatchAny:        false,
			NonEmptyAttrs:   map[string]bool{"srcs": true},
			SubstituteAttrs: map[string]bool{},
			MergeableAttrs:  map[string]bool{"srcs": true, "modules": true},
			ResolveAttrs:    map[string]bool{},
		},
		tfTestKind: {
			MatchAny:        false,
			NonEmptyAttrs:   map[string]bool{"test_files": true},
			SubstituteAttrs: map[string]bool{},
			MergeableAttrs:  map[string]bool{"test_files": true},
			ResolveAttrs:    map[string]bool{"module": true},
		},
	}
}

// Loads returns the load statements needed for rules generated by this language.
// Uses the module name from MODULE.bazel to generate correct load paths.
// This works both when used as root module (bzlmod self-reference) and as external dependency.
func (l *terraformLang) Loads() []rule.LoadInfo {
	moduleName := l.getModuleName()
	return []rule.LoadInfo{
		{
			Name:    "@" + moduleName + "//tf2:def.bzl",
			Symbols: []string{tfModuleKind, tfStackKind, tfTestKind},
		},
	}
}

// RegisterFlags registers command-line flags used by the extension.
func (l *terraformLang) RegisterFlags(fs *flag.FlagSet, cmd string, c *config.Config) {}

// CheckFlags validates the command-line flags.
func (l *terraformLang) CheckFlags(fs *flag.FlagSet, c *config.Config) error {
	return nil
}

// KnownDirectives returns the directives that are recognized by this language.
func (l *terraformLang) KnownDirectives() []string {
	return []string{
		"terraform_enabled",
		"terraform_provider",
	}
}

// Configure applies configuration from directives.
func (l *terraformLang) Configure(c *config.Config, rel string, f *rule.File) {
	// Store repo root for MODULE.bazel parsing (used by Loads())
	if l.repoRoot == "" && c.RepoRoot != "" {
		l.repoRoot = c.RepoRoot
	}

	cfg := newTerraformConfig()
	if raw := c.Exts[terraformName]; raw != nil {
		cfg = raw.(*terraformConfig)
	}

	if f != nil {
		for _, d := range f.Directives {
			switch d.Key {
			case "terraform_enabled":
				cfg.enabled = d.Value != "false"
			case "terraform_provider":
				// Format: "provider_name label"
				parts := strings.Fields(d.Value)
				if len(parts) >= 2 {
					cfg.providerMapping[parts[0]] = parts[1]
				}
			}
		}
	}

	c.Exts[terraformName] = cfg
}

// GenerateRules generates tf_module, tf_stack, and tf_test rules for directories containing .tf or .tfcomponent.hcl files.
func (l *terraformLang) GenerateRules(args language.GenerateArgs) language.GenerateResult {
	cfg := getConfig(args.Config)
	if !cfg.enabled {
		return language.GenerateResult{}
	}

	// Categorize files
	var tfFiles []string
	var testFiles []string
	var templateFiles []string
	var componentFiles []string
	var deployFiles []string
	var dataFiles []string
	var hasReadme bool
	var hasTerraformTf bool

	for _, f := range args.RegularFiles {
		switch {
		case strings.HasSuffix(f, ".tftest.hcl") || strings.HasSuffix(f, ".tftest.json"):
			testFiles = append(testFiles, f)
		case strings.HasSuffix(f, ".tfcomponent.hcl"):
			componentFiles = append(componentFiles, f)
		case strings.HasSuffix(f, ".tfdeploy.hcl"):
			deployFiles = append(deployFiles, f)
		case strings.HasSuffix(f, ".tf"):
			tfFiles = append(tfFiles, f)
			if f == "terraform.tf" {
				hasTerraformTf = true
			}
		case strings.HasSuffix(f, ".tmpl") || strings.HasSuffix(f, ".tpl") || strings.HasSuffix(f, ".tftpl"):
			templateFiles = append(templateFiles, f)
		case strings.HasSuffix(f, ".json"):
			dataFiles = append(dataFiles, f)
		case f == "README.md":
			hasReadme = true
		}
	}

	// No .tf files and no component files, no rules to generate
	if len(tfFiles) == 0 && len(componentFiles) == 0 {
		return language.GenerateResult{}
	}

	// Extract module references from .tf files
	detectedModules := extractModulesFromTfFiles(args.Dir, tfFiles, args.Rel)

	var rules []*rule.Rule
	var imports []interface{}

	// Find existing rules by kind (not by name)
	var existingModule, existingStack, existingTest *rule.Rule
	if args.File != nil {
		for _, r := range args.File.Rules {
			switch r.Kind() {
			case tfModuleKind:
				existingModule = r
			case tfStackKind:
				existingStack = r
			case tfTestKind:
				existingTest = r
			}
		}
	}

	// Generate tf_module rule if .tf files exist
	if len(tfFiles) > 0 {
		moduleRule := generateModuleRule(defaultModuleName, tfFiles, templateFiles, hasReadme, hasTerraformTf, args.Dir, cfg, existingModule, detectedModules)
		rules = append(rules, moduleRule)
		imports = append(imports, nil)
	}

	// Generate tf_stack rule if component files exist
	if len(componentFiles) > 0 {
		detectedStackModules := extractComponentSources(args.Dir, componentFiles, args.Rel)
		stackRule := generateStackRule(defaultStackName, componentFiles, deployFiles, dataFiles, args.Dir, existingStack, detectedStackModules)
		rules = append(rules, stackRule)
		imports = append(imports, nil)
	}

	// Generate tf_test rule if test files exist
	// Always generate explicit tf_test when .tftest.hcl files are present
	if len(testFiles) > 0 {
		testRule := generateTestRule(defaultTestName, defaultModuleName, testFiles, existingTest)
		rules = append(rules, testRule)
		imports = append(imports, nil)
	}

	return language.GenerateResult{
		Gen:     rules,
		Imports: imports,
	}
}

// generateModuleRule creates a tf_module rule.
func generateModuleRule(name string, tfFiles []string, templateFiles []string, hasReadme, hasTerraformTf bool, dir string, cfg *terraformConfig, existing *rule.Rule, detectedModules []string) *rule.Rule {
	r := rule.NewRule(tfModuleKind, name)

	// Build srcs list
	// Sort files for deterministic output
	sort.Strings(tfFiles)
	sort.Strings(templateFiles)

	// Build explicit source list with .tf files, templates, and README
	srcs := make([]string, 0, len(tfFiles)+len(templateFiles)+1)
	srcs = append(srcs, tfFiles...)
	srcs = append(srcs, templateFiles...)
	if hasReadme {
		srcs = append(srcs, "README.md")
	}
	sort.Strings(srcs)
	r.SetAttr("srcs", srcs)

	// Extract providers from terraform.tf
	if hasTerraformTf {
		providers := extractProvidersFromTerraformTf(filepath.Join(dir, "terraform.tf"), cfg)
		if len(providers) > 0 {
			r.SetAttr("providers", providers)
		}
	}

	// Merge detected modules with existing modules
	finalModules := mergeModules(detectedModules, existing)
	if len(finalModules) > 0 {
		r.SetAttr("modules", finalModules)
	}

	// Preserve existing attributes
	if existing != nil {
		// Keep providers if set manually and we didn't extract any
		if existing.Attr("providers") != nil && r.Attr("providers") == nil {
			r.SetAttr("providers", existing.Attr("providers"))
		}
		// Keep tflint_config if set
		if existing.Attr("tflint_config") != nil {
			r.SetAttr("tflint_config", existing.Attr("tflint_config"))
		}
		// Keep tfdoc_config if set
		if existing.Attr("tfdoc_config") != nil {
			r.SetAttr("tfdoc_config", existing.Attr("tfdoc_config"))
		}
		// Keep visibility if set
		if existing.Attr("visibility") != nil {
			r.SetAttr("visibility", existing.Attr("visibility"))
		}
		// Keep skip_validation if set
		if existing.Attr("skip_validation") != nil {
			r.SetAttr("skip_validation", existing.Attr("skip_validation"))
		}
		// Keep tags if set
		if existing.Attr("tags") != nil {
			r.SetAttr("tags", existing.Attr("tags"))
		}
		// Keep testonly if set
		if existing.Attr("testonly") != nil {
			r.SetAttr("testonly", existing.Attr("testonly"))
		}
	}

	return r
}

// mergeModules combines detected modules with existing manual modules.
// Detected modules take precedence, but manual entries not detected are preserved.
func mergeModules(detected []string, existing *rule.Rule) []string {
	seen := make(map[string]bool)
	var result []string

	// Add all detected modules
	for _, m := range detected {
		if !seen[m] {
			seen[m] = true
			result = append(result, m)
		}
	}

	// Add existing modules that weren't detected (manual entries)
	if existing != nil && existing.Attr("modules") != nil {
		existingModules := existing.AttrStrings("modules")
		for _, m := range existingModules {
			// Normalize the label for comparison
			normalized := m
			if !seen[normalized] {
				seen[normalized] = true
				result = append(result, m)
			}
		}
	}

	sort.Strings(result)
	return result
}

// generateTestRule creates a tf_test rule.
func generateTestRule(testName, moduleName string, testFiles []string, existing *rule.Rule) *rule.Rule {
	r := rule.NewRule(tfTestKind, testName)

	// Sort test files for deterministic output
	sort.Strings(testFiles)

	// Set module reference
	r.SetAttr("module", ":"+moduleName)

	// Set test_files
	r.SetAttr("test_files", testFiles)

	// Preserve existing attributes
	if existing != nil {
		// Keep data if set
		if existing.Attr("data") != nil {
			r.SetAttr("data", existing.Attr("data"))
		}
		// Keep size if set
		if existing.Attr("size") != nil {
			r.SetAttr("size", existing.Attr("size"))
		}
		// Keep tags if set
		if existing.Attr("tags") != nil {
			r.SetAttr("tags", existing.Attr("tags"))
		}
		// Keep visibility if set
		if existing.Attr("visibility") != nil {
			r.SetAttr("visibility", existing.Attr("visibility"))
		}
	}

	return r
}

// Fix repairs incorrect rules.
func (l *terraformLang) Fix(c *config.Config, f *rule.File) {}

// Imports returns the imports for dependency resolution.
func (l *terraformLang) Imports(c *config.Config, r *rule.Rule, f *rule.File) []resolve.ImportSpec {
	return nil
}

// Embeds returns the labels for embedded dependencies.
func (l *terraformLang) Embeds(r *rule.Rule, from label.Label) []label.Label {
	return nil
}

// Resolve resolves dependencies.
func (l *terraformLang) Resolve(c *config.Config, ix *resolve.RuleIndex, rc *repo.RemoteCache, r *rule.Rule, imports interface{}, from label.Label) {
}

// getConfig retrieves the terraform configuration from the config.
func getConfig(c *config.Config) *terraformConfig {
	if raw := c.Exts[terraformName]; raw != nil {
		return raw.(*terraformConfig)
	}
	return newTerraformConfig()
}

// extractProvidersFromTerraformTf extracts provider requirements from terraform.tf.
func extractProvidersFromTerraformTf(path string, cfg *terraformConfig) []string {
	content, err := os.ReadFile(path)
	if err != nil {
		return nil
	}

	// Simple parsing: look for required_providers block
	// This is a simplified parser - in production, use HCL parser
	providers := []string{}
	lines := strings.Split(string(content), "\n")
	inRequiredProviders := false

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		if strings.Contains(trimmed, "required_providers") {
			inRequiredProviders = true
			continue
		}

		if inRequiredProviders {
			if trimmed == "}" {
				break
			}
			// Look for provider name = { pattern
			if strings.Contains(trimmed, "=") && strings.Contains(trimmed, "{") {
				parts := strings.Split(trimmed, "=")
				if len(parts) >= 1 {
					providerName := strings.TrimSpace(parts[0])
					// Check if we have a mapping
					if label, ok := cfg.providerMapping[providerName]; ok {
						providers = append(providers, label)
					}
				}
			}
		}
	}

	return providers
}

// extractModulesFromTfFiles extracts relative module references from .tf files.
// It looks for module blocks with source attributes pointing to relative paths.
func extractModulesFromTfFiles(dir string, tfFiles []string, currentPackage string) []string {
	var modules []string
	seen := make(map[string]bool)

	// Regex to match source = "..." in module blocks
	// This is a simplified parser - matches any source attribute
	sourceRegex := regexp.MustCompile(`source\s*=\s*"([^"]+)"`)

	for _, tfFile := range tfFiles {
		path := filepath.Join(dir, tfFile)
		content, err := os.ReadFile(path)
		if err != nil {
			continue
		}

		matches := sourceRegex.FindAllStringSubmatch(string(content), -1)
		for _, match := range matches {
			if len(match) < 2 {
				continue
			}
			source := match[1]

			// Only process relative paths (starting with ./ or ../)
			if !strings.HasPrefix(source, "./") && !strings.HasPrefix(source, "../") {
				continue
			}

			// Skip if it looks like a remote module
			if isRemoteModuleSource(source) {
				continue
			}

			label := resolveModuleSourceToLabel(source, currentPackage)
			if label != "" && !seen[label] {
				seen[label] = true
				modules = append(modules, label)
			}
		}
	}

	sort.Strings(modules)
	return modules
}

// isRemoteModuleSource checks if a source looks like a remote module reference.
func isRemoteModuleSource(source string) bool {
	// Remote module patterns to filter out
	remotePatterns := []string{
		"git::",
		"hg::",
		"s3::",
		"gcs::",
		"https://",
		"http://",
		"registry.terraform.io",
	}
	for _, pattern := range remotePatterns {
		if strings.Contains(source, pattern) {
			return true
		}
	}
	// Registry modules like "hashicorp/consul/aws"
	if strings.Count(source, "/") >= 2 && !strings.HasPrefix(source, ".") {
		return true
	}
	return false
}

// resolveModuleSourceToLabel converts a relative module source to a Bazel label.
// e.g., "./modules/foo" -> "//current/package/modules/foo:tf_module"
// e.g., "../sibling" -> "//parent/sibling:tf_module"
func resolveModuleSourceToLabel(source, currentPackage string) string {
	// Handle empty package (root)
	if currentPackage == "" {
		// Remove leading ./
		source = strings.TrimPrefix(source, "./")
		if strings.HasPrefix(source, "../") {
			// Can't go above root
			return ""
		}
		return "//" + source + ":tf_module"
	}

	// Split current package into parts
	parts := strings.Split(currentPackage, "/")

	// Handle ./ prefix
	if strings.HasPrefix(source, "./") {
		source = strings.TrimPrefix(source, "./")
		finalPath := currentPackage + "/" + source
		return "//" + finalPath + ":tf_module"
	}

	// Handle ../ prefix - go up directories
	sourceParts := strings.Split(source, "/")
	for len(sourceParts) > 0 && sourceParts[0] == ".." {
		sourceParts = sourceParts[1:]
		if len(parts) > 0 {
			parts = parts[:len(parts)-1]
		}
	}

	// Combine remaining parts
	var finalPath string
	if len(parts) > 0 {
		finalPath = strings.Join(parts, "/") + "/" + strings.Join(sourceParts, "/")
	} else {
		finalPath = strings.Join(sourceParts, "/")
	}

	return "//" + finalPath + ":tf_module"
}

// generateStackRule creates a tf_stack rule.
func generateStackRule(name string, componentFiles, deployFiles, dataFiles []string, dir string, existing *rule.Rule, detectedModules []string) *rule.Rule {
	r := rule.NewRule(tfStackKind, name)

	// Build srcs list - combine all stack files
	sort.Strings(componentFiles)
	sort.Strings(deployFiles)
	sort.Strings(dataFiles)

	srcs := make([]string, 0, len(componentFiles)+len(deployFiles)+len(dataFiles))
	srcs = append(srcs, componentFiles...)
	srcs = append(srcs, deployFiles...)
	srcs = append(srcs, dataFiles...)
	r.SetAttr("srcs", srcs)

	// Set detected modules
	finalModules := mergeStackModules(detectedModules, existing)
	if len(finalModules) > 0 {
		r.SetAttr("modules", finalModules)
	}

	// Preserve existing attributes
	if existing != nil {
		// Keep visibility if set
		if existing.Attr("visibility") != nil {
			r.SetAttr("visibility", existing.Attr("visibility"))
		}
		// Keep skip_validation if set
		if existing.Attr("skip_validation") != nil {
			r.SetAttr("skip_validation", existing.Attr("skip_validation"))
		}
		// Keep tags if set
		if existing.Attr("tags") != nil {
			r.SetAttr("tags", existing.Attr("tags"))
		}
		// Keep testonly if set
		if existing.Attr("testonly") != nil {
			r.SetAttr("testonly", existing.Attr("testonly"))
		}
		// Keep terraform_version if set
		if existing.Attr("terraform_version") != nil {
			r.SetAttr("terraform_version", existing.Attr("terraform_version"))
		}
	}

	return r
}

// mergeStackModules combines detected modules with existing manual modules.
func mergeStackModules(detected []string, existing *rule.Rule) []string {
	seen := make(map[string]bool)
	var result []string

	// Add all detected modules
	for _, m := range detected {
		if !seen[m] {
			seen[m] = true
			result = append(result, m)
		}
	}

	// Add existing modules that weren't detected (manual entries)
	if existing != nil && existing.Attr("modules") != nil {
		existingModules := existing.AttrStrings("modules")
		for _, m := range existingModules {
			if !seen[m] {
				seen[m] = true
				result = append(result, m)
			}
		}
	}

	sort.Strings(result)
	return result
}

// extractComponentSources extracts module references from .tfcomponent.hcl files.
// It looks for component blocks with source attributes pointing to relative paths.
func extractComponentSources(dir string, componentFiles []string, currentPackage string) []string {
	var modules []string
	seen := make(map[string]bool)

	// Regex to match source = "..." inside component blocks
	// This matches: component "name" { ... source = "path" ... }
	sourceRegex := regexp.MustCompile(`source\s*=\s*"([^"]+)"`)

	for _, compFile := range componentFiles {
		path := filepath.Join(dir, compFile)
		content, err := os.ReadFile(path)
		if err != nil {
			continue
		}

		matches := sourceRegex.FindAllStringSubmatch(string(content), -1)
		for _, match := range matches {
			if len(match) < 2 {
				continue
			}
			source := match[1]

			// Only process relative paths (starting with ./ or ../)
			if !strings.HasPrefix(source, "./") && !strings.HasPrefix(source, "../") {
				continue
			}

			// Skip if it looks like a remote module
			if isRemoteModuleSource(source) {
				continue
			}

			label := resolveModuleSourceToLabel(source, currentPackage)
			if label != "" && !seen[label] {
				seen[label] = true
				modules = append(modules, label)
			}
		}
	}

	sort.Strings(modules)
	return modules
}
