// Package terraform provides a Gazelle language extension for Terraform modules.
package terraform

import (
	"flag"
	"os"
	"path/filepath"
	"strings"

	"github.com/bazelbuild/bazel-gazelle/config"
	"github.com/bazelbuild/bazel-gazelle/label"
	"github.com/bazelbuild/bazel-gazelle/language"
	"github.com/bazelbuild/bazel-gazelle/repo"
	"github.com/bazelbuild/bazel-gazelle/resolve"
	"github.com/bazelbuild/bazel-gazelle/rule"
)

const (
	terraformName = "terraform"
	tfModuleKind  = "tf_module"
)

// NewLanguage creates a new Gazelle language extension for Terraform.
func NewLanguage() language.Language {
	return &terraformLang{}
}

type terraformLang struct{}

// terraformConfig holds configuration for the terraform extension.
type terraformConfig struct {
	enabled         bool
	providerMapping map[string]string // Maps provider names to registry labels
}

func newTerraformConfig() *terraformConfig {
	return &terraformConfig{
		enabled:         true,
		providerMapping: make(map[string]string),
	}
}

// Name returns the name of the language.
func (l *terraformLang) Name() string { return terraformName }

// Kinds returns the kinds of rules generated by this language.
func (l *terraformLang) Kinds() map[string]rule.KindInfo {
	return map[string]rule.KindInfo{
		tfModuleKind: {
			MatchAny:       false,
			NonEmptyAttrs:  map[string]bool{"srcs": true, "providers": true},
			SubstituteAttrs: map[string]bool{},
			MergeableAttrs: map[string]bool{"srcs": true, "providers": true},
			ResolveAttrs:   map[string]bool{},
		},
	}
}

// Loads returns the load statements needed for rules generated by this language.
func (l *terraformLang) Loads() []rule.LoadInfo {
	return []rule.LoadInfo{
		{
			Name:    "//tf2:def.bzl",
			Symbols: []string{tfModuleKind},
		},
	}
}

// RegisterFlags registers command-line flags used by the extension.
func (l *terraformLang) RegisterFlags(fs *flag.FlagSet, cmd string, c *config.Config) {}

// CheckFlags validates the command-line flags.
func (l *terraformLang) CheckFlags(fs *flag.FlagSet, c *config.Config) error {
	return nil
}

// KnownDirectives returns the directives that are recognized by this language.
func (l *terraformLang) KnownDirectives() []string {
	return []string{
		"terraform_enabled",
		"terraform_provider",
	}
}

// Configure applies configuration from directives.
func (l *terraformLang) Configure(c *config.Config, rel string, f *rule.File) {
	cfg := newTerraformConfig()
	if raw := c.Exts[terraformName]; raw != nil {
		cfg = raw.(*terraformConfig)
	}

	if f != nil {
		for _, d := range f.Directives {
			switch d.Key {
			case "terraform_enabled":
				cfg.enabled = d.Value != "false"
			case "terraform_provider":
				// Format: "provider_name label"
				parts := strings.Fields(d.Value)
				if len(parts) >= 2 {
					cfg.providerMapping[parts[0]] = parts[1]
				}
			}
		}
	}

	c.Exts[terraformName] = cfg
}

// GenerateRules generates tf_module rules for directories containing .tf files.
func (l *terraformLang) GenerateRules(args language.GenerateArgs) language.GenerateResult {
	cfg := getConfig(args.Config)
	if !cfg.enabled {
		return language.GenerateResult{}
	}

	// Find .tf files
	var tfFiles []string
	var hasReadme bool
	var hasTfdocConfig bool
	var hasTerraformTf bool

	for _, f := range args.RegularFiles {
		if strings.HasSuffix(f, ".tf") {
			tfFiles = append(tfFiles, f)
			if f == "terraform.tf" {
				hasTerraformTf = true
			}
		}
		if f == "README.md" {
			hasReadme = true
		}
		if f == ".tfdoc.yaml" || f == ".terraform-docs.yml" {
			hasTfdocConfig = true
		}
	}

	// No .tf files, no rule to generate
	if len(tfFiles) == 0 {
		return language.GenerateResult{}
	}

	// Check if there's already a tf_module rule
	var existingRule *rule.Rule
	if args.File != nil {
		for _, r := range args.File.Rules {
			if r.Kind() == tfModuleKind {
				existingRule = r
				break
			}
		}
	}

	// Generate the rule
	r := rule.NewRule(tfModuleKind, inferModuleName(args.Rel))

	// Build srcs list - use GlobValue with extra files if README exists
	globValue := rule.GlobValue{
		Patterns: []string{"*.tf"},
	}
	r.SetAttr("srcs", globValue)

	// Note: Gazelle doesn't easily support "glob + list" expressions
	// For now, just use the glob. Users can manually add README.md if needed.
	// TODO: Consider using a custom expression type or post-processing
	_ = hasReadme       // Suppress unused variable warning for now
	_ = hasTfdocConfig  // Suppress unused variable warning for now

	// Try to extract providers from terraform.tf
	if hasTerraformTf {
		providers := extractProvidersFromTerraformTf(filepath.Join(args.Dir, "terraform.tf"), cfg)
		if len(providers) > 0 {
			r.SetAttr("providers", providers)
		}
	}

	// Preserve existing attributes from existing rule
	if existingRule != nil {
		// Keep providers if set manually
		if existingRule.Attr("providers") != nil && r.Attr("providers") == nil {
			r.SetAttr("providers", existingRule.Attr("providers"))
		}
		// Keep tflint_config if set
		if existingRule.Attr("tflint_config") != nil {
			r.SetAttr("tflint_config", existingRule.Attr("tflint_config"))
		}
		// Keep tfdoc_config if set
		if existingRule.Attr("tfdoc_config") != nil {
			r.SetAttr("tfdoc_config", existingRule.Attr("tfdoc_config"))
		}
		// Keep visibility if set
		if existingRule.Attr("visibility") != nil {
			r.SetAttr("visibility", existingRule.Attr("visibility"))
		}
	}

	return language.GenerateResult{
		Gen:     []*rule.Rule{r},
		Imports: []interface{}{nil},
	}
}

// Fix repairs incorrect rules.
func (l *terraformLang) Fix(c *config.Config, f *rule.File) {}

// Imports returns the imports for dependency resolution.
func (l *terraformLang) Imports(c *config.Config, r *rule.Rule, f *rule.File) []resolve.ImportSpec {
	return nil
}

// Embeds returns the labels for embedded dependencies.
func (l *terraformLang) Embeds(r *rule.Rule, from label.Label) []label.Label {
	return nil
}

// Resolve resolves dependencies.
func (l *terraformLang) Resolve(c *config.Config, ix *resolve.RuleIndex, rc *repo.RemoteCache, r *rule.Rule, imports interface{}, from label.Label) {
}

// getConfig retrieves the terraform configuration from the config.
func getConfig(c *config.Config) *terraformConfig {
	if raw := c.Exts[terraformName]; raw != nil {
		return raw.(*terraformConfig)
	}
	return newTerraformConfig()
}

// inferModuleName infers the module name from the relative path.
func inferModuleName(rel string) string {
	if rel == "" {
		return "root"
	}
	return filepath.Base(rel)
}

// extractProvidersFromTerraformTf extracts provider requirements from terraform.tf.
func extractProvidersFromTerraformTf(path string, cfg *terraformConfig) []string {
	content, err := os.ReadFile(path)
	if err != nil {
		return nil
	}

	// Simple parsing: look for required_providers block
	// This is a simplified parser - in production, use HCL parser
	providers := []string{}
	lines := strings.Split(string(content), "\n")
	inRequiredProviders := false

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		if strings.Contains(trimmed, "required_providers") {
			inRequiredProviders = true
			continue
		}

		if inRequiredProviders {
			if trimmed == "}" {
				break
			}
			// Look for provider name = { pattern
			if strings.Contains(trimmed, "=") && strings.Contains(trimmed, "{") {
				parts := strings.Split(trimmed, "=")
				if len(parts) >= 1 {
					providerName := strings.TrimSpace(parts[0])
					// Check if we have a mapping
					if label, ok := cfg.providerMapping[providerName]; ok {
						providers = append(providers, label)
					}
				}
			}
		}
	}

	return providers
}
