// Package terraform provides a Gazelle language extension for Terraform modules.
package terraform

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"sync"

	"github.com/bazelbuild/bazel-gazelle/config"
	"github.com/bazelbuild/bazel-gazelle/label"
	"github.com/bazelbuild/bazel-gazelle/language"
	"github.com/bazelbuild/bazel-gazelle/repo"
	"github.com/bazelbuild/bazel-gazelle/resolve"
	"github.com/bazelbuild/bazel-gazelle/rule"
)

const (
	terraformName     = "terraform"
	tfModuleKind      = "tf_module"
	tfTestKind        = "tf_test"
	defaultModuleName = "tf_module" // Default name for tf_module rules
	defaultTestName   = "tf_test"   // Default name for tf_test rules
)

// NewLanguage creates a new Gazelle language extension for Terraform.
func NewLanguage() language.Language {
	return &terraformLang{}
}

type terraformLang struct {
	// moduleName is the bzlmod module name parsed from MODULE.bazel
	// Used to generate correct load statements like @module_name//tf2:def.bzl
	moduleName     string
	moduleNameOnce sync.Once
	repoRoot       string
}

// terraformConfig holds configuration for the terraform extension.
type terraformConfig struct {
	enabled            bool
	providerMapping    map[string]string // Maps provider names to registry labels
	ignoreFileWarnings map[string]bool   // Filenames to ignore in warnings (dynamic paths by design)
}

func newTerraformConfig() *terraformConfig {
	return &terraformConfig{
		enabled:            true,
		providerMapping:    make(map[string]string),
		ignoreFileWarnings: make(map[string]bool),
	}
}

// parseModuleNameFromFile extracts the module name from a MODULE.bazel file.
// Returns empty string if the file doesn't exist or can't be parsed.
func parseModuleNameFromFile(path string) string {
	content, err := os.ReadFile(path)
	if err != nil {
		return ""
	}

	// Look for: module(name = "module_name", ...)
	// Simple regex to extract the name attribute
	moduleRegex := regexp.MustCompile(`module\s*\(\s*name\s*=\s*"([^"]+)"`)
	matches := moduleRegex.FindStringSubmatch(string(content))
	if len(matches) >= 2 {
		return matches[1]
	}

	return ""
}

// getModuleName returns the bzlmod module name, parsing MODULE.bazel if needed.
func (l *terraformLang) getModuleName() string {
	l.moduleNameOnce.Do(func() {
		if l.repoRoot != "" {
			modulePath := filepath.Join(l.repoRoot, "MODULE.bazel")
			l.moduleName = parseModuleNameFromFile(modulePath)
		}
		// Fallback to rules_tf2 if we couldn't parse the module name
		if l.moduleName == "" {
			l.moduleName = "rules_tf2"
		}
	})
	return l.moduleName
}

// Name returns the name of the language.
func (l *terraformLang) Name() string { return terraformName }

// Kinds returns the kinds of rules generated by this language.
func (l *terraformLang) Kinds() map[string]rule.KindInfo {
	return map[string]rule.KindInfo{
		tfModuleKind: {
			MatchAny:        false,
			NonEmptyAttrs:   map[string]bool{"srcs": true, "providers": true},
			SubstituteAttrs: map[string]bool{"srcs": true}, // Replace globs with explicit file lists
			MergeableAttrs:  map[string]bool{"srcs": true}, // Allow gazelle to update srcs
			ResolveAttrs:    map[string]bool{},
		},
		tfTestKind: {
			MatchAny:        false,
			NonEmptyAttrs:   map[string]bool{"test_files": true},
			SubstituteAttrs: map[string]bool{"test_files": true}, // Replace globs with explicit file lists
			MergeableAttrs:  map[string]bool{"test_files": true}, // Allow gazelle to update test_files
			ResolveAttrs:    map[string]bool{"module": true},
		},
	}
}

// Loads returns the load statements needed for rules generated by this language.
// Uses the module name from MODULE.bazel to generate correct load paths.
// This works both when used as root module (bzlmod self-reference) and as external dependency.
func (l *terraformLang) Loads() []rule.LoadInfo {
	moduleName := l.getModuleName()
	return []rule.LoadInfo{
		{
			Name:    "@" + moduleName + "//tf2:def.bzl",
			Symbols: []string{tfModuleKind, tfTestKind},
		},
	}
}

// RegisterFlags registers command-line flags used by the extension.
func (l *terraformLang) RegisterFlags(fs *flag.FlagSet, cmd string, c *config.Config) {}

// CheckFlags validates the command-line flags.
func (l *terraformLang) CheckFlags(fs *flag.FlagSet, c *config.Config) error {
	return nil
}

// KnownDirectives returns the directives that are recognized by this language.
func (l *terraformLang) KnownDirectives() []string {
	return []string{
		"terraform_enabled",
		"terraform_provider",
		"terraform_ignore_file_warning",
	}
}

// Configure applies configuration from directives.
func (l *terraformLang) Configure(c *config.Config, rel string, f *rule.File) {
	// Store repo root for MODULE.bazel parsing (used by Loads())
	if l.repoRoot == "" && c.RepoRoot != "" {
		l.repoRoot = c.RepoRoot
	}

	cfg := newTerraformConfig()
	if raw := c.Exts[terraformName]; raw != nil {
		cfg = raw.(*terraformConfig)
	}

	if f != nil {
		for _, d := range f.Directives {
			switch d.Key {
			case "terraform_enabled":
				cfg.enabled = d.Value != "false"
			case "terraform_provider":
				// Format: "provider_name label"
				parts := strings.Fields(d.Value)
				if len(parts) >= 2 {
					cfg.providerMapping[parts[0]] = parts[1]
				}
			case "terraform_ignore_file_warning":
				// Format: "filename.ext" - suppress warnings for files with dynamic paths
				filename := strings.TrimSpace(d.Value)
				if filename != "" {
					cfg.ignoreFileWarnings[filename] = true
				}
			}
		}
	}

	c.Exts[terraformName] = cfg
}

// GenerateRules generates tf_module and tf_test rules for directories containing .tf files.
func (l *terraformLang) GenerateRules(args language.GenerateArgs) language.GenerateResult {
	cfg := getConfig(args.Config)
	if !cfg.enabled {
		return language.GenerateResult{}
	}

	// Categorize files
	var tfFiles []string
	var testFiles []string
	var templateFiles []string
	var hasReadme bool
	var hasTerraformTf bool

	for _, f := range args.RegularFiles {
		switch {
		case strings.HasSuffix(f, ".tftest.hcl") || strings.HasSuffix(f, ".tftest.json"):
			testFiles = append(testFiles, f)
		case strings.HasSuffix(f, ".tf"):
			tfFiles = append(tfFiles, f)
			if f == "terraform.tf" {
				hasTerraformTf = true
			}
		case strings.HasSuffix(f, ".tmpl") || strings.HasSuffix(f, ".tpl") || strings.HasSuffix(f, ".tftpl"):
			templateFiles = append(templateFiles, f)
		case f == "README.md":
			hasReadme = true
		}
	}

	// No .tf files, no rules to generate
	if len(tfFiles) == 0 {
		return language.GenerateResult{}
	}

	// Extract module references from .tf files
	detectedModules := extractModulesFromTfFiles(args.Dir, tfFiles, args.Rel)

	// Extract file references from .tf files (templatefile, file, etc.)
	srcFileResult := extractFileReferencesFromTfFiles(args.Dir, tfFiles)

	// Extract file references from test files
	testFileResult := extractFileReferencesFromTestFiles(args.Dir, testFiles)

	// Print warnings for files that need manual addition (filtered by ignore list)
	for _, w := range srcFileResult.warnings {
		if !cfg.ignoreFileWarnings[w] {
			fmt.Fprintf(os.Stderr, "gazelle: %s: file %q referenced with dynamic path - add to srcs manually, or if this file only exists at runtime add to BUILD: # gazelle:terraform_ignore_file_warning %s\n", args.Rel, w, w)
		}
	}
	for _, w := range testFileResult.warnings {
		if !cfg.ignoreFileWarnings[w] {
			fmt.Fprintf(os.Stderr, "gazelle: %s: file %q referenced with dynamic path - add to test_files manually, or if this file only exists at runtime add to BUILD: # gazelle:terraform_ignore_file_warning %s\n", args.Rel, w, w)
		}
	}

	var rules []*rule.Rule
	var imports []interface{}

	// Find existing rules by kind (not by name)
	var existingModule, existingTest *rule.Rule
	if args.File != nil {
		for _, r := range args.File.Rules {
			switch r.Kind() {
			case tfModuleKind:
				existingModule = r
			case tfTestKind:
				existingTest = r
			}
		}
	}

	// Generate tf_module rule if .tf files exist
	if len(tfFiles) > 0 {
		moduleRule := generateModuleRule(defaultModuleName, tfFiles, templateFiles, srcFileResult.files, hasReadme, hasTerraformTf, args.Dir, cfg, existingModule, detectedModules)
		rules = append(rules, moduleRule)
		imports = append(imports, nil)
	}

	// Generate tf_test rule if test files exist
	// Always generate explicit tf_test when .tftest.hcl files are present
	if len(testFiles) > 0 {
		testRule := generateTestRule(defaultTestName, defaultModuleName, testFiles, testFileResult.files, existingTest)
		rules = append(rules, testRule)
		imports = append(imports, nil)
	}

	return language.GenerateResult{
		Gen:     rules,
		Imports: imports,
	}
}

// generateModuleRule creates a tf_module rule.
func generateModuleRule(name string, tfFiles []string, templateFiles []string, referencedFiles []string, hasReadme, hasTerraformTf bool, dir string, cfg *terraformConfig, existing *rule.Rule, detectedModules []string) *rule.Rule {
	r := rule.NewRule(tfModuleKind, name)

	// Build srcs list
	// Sort files for deterministic output
	sort.Strings(tfFiles)
	sort.Strings(templateFiles)

	// Build explicit source list with .tf files, templates, and README
	srcs := make([]string, 0, len(tfFiles)+len(templateFiles)+len(referencedFiles)+1)
	srcs = append(srcs, tfFiles...)
	srcs = append(srcs, templateFiles...)

	// Add referenced files from file() and templatefile() calls (excluding Bazel labels)
	for _, f := range referencedFiles {
		if !isBazelLabel(f) {
			srcs = append(srcs, f)
		}
	}

	if hasReadme {
		srcs = append(srcs, "README.md")
	}

	// Deduplicate and sort
	srcs = deduplicateStrings(srcs)
	sort.Strings(srcs)
	r.SetAttr("srcs", srcs)

	// Extract providers from terraform.tf
	if hasTerraformTf {
		providers := extractProvidersFromTerraformTf(filepath.Join(dir, "terraform.tf"), cfg)
		if len(providers) > 0 {
			r.SetAttr("providers", providers)
		}
	}

	// Merge detected modules with existing modules
	finalModules := mergeModules(detectedModules, existing)
	if len(finalModules) > 0 {
		r.SetAttr("modules", finalModules)
	}

	// Preserve existing attributes
	if existing != nil {
		// Keep providers if set manually and we didn't extract any
		if existing.Attr("providers") != nil && r.Attr("providers") == nil {
			r.SetAttr("providers", existing.Attr("providers"))
		}
		// Keep tflint_config if set
		if existing.Attr("tflint_config") != nil {
			r.SetAttr("tflint_config", existing.Attr("tflint_config"))
		}
		// Keep tfdoc_config if set
		if existing.Attr("tfdoc_config") != nil {
			r.SetAttr("tfdoc_config", existing.Attr("tfdoc_config"))
		}
		// Keep visibility if set
		if existing.Attr("visibility") != nil {
			r.SetAttr("visibility", existing.Attr("visibility"))
		}
		// Keep skip_validation if set
		if existing.Attr("skip_validation") != nil {
			r.SetAttr("skip_validation", existing.Attr("skip_validation"))
		}
		// Keep tags if set
		if existing.Attr("tags") != nil {
			r.SetAttr("tags", existing.Attr("tags"))
		}
		// Keep testonly if set
		if existing.Attr("testonly") != nil {
			r.SetAttr("testonly", existing.Attr("testonly"))
		}
	}

	return r
}

// mergeModules combines detected modules with existing manual modules.
// Detected modules take precedence, but manual entries not detected are preserved.
func mergeModules(detected []string, existing *rule.Rule) []string {
	seen := make(map[string]bool)
	var result []string

	// Add all detected modules
	for _, m := range detected {
		if !seen[m] {
			seen[m] = true
			result = append(result, m)
		}
	}

	// Add existing modules that weren't detected (manual entries)
	if existing != nil && existing.Attr("modules") != nil {
		existingModules := existing.AttrStrings("modules")
		for _, m := range existingModules {
			// Normalize the label for comparison
			normalized := m
			if !seen[normalized] {
				seen[normalized] = true
				result = append(result, m)
			}
		}
	}

	sort.Strings(result)
	return result
}

// generateTestRule creates a tf_test rule.
func generateTestRule(testName, moduleName string, testFiles []string, referencedFiles []string, existing *rule.Rule) *rule.Rule {
	r := rule.NewRule(tfTestKind, testName)

	// Build test_files list - combine test files with referenced files
	allTestFiles := make([]string, 0, len(testFiles)+len(referencedFiles))
	allTestFiles = append(allTestFiles, testFiles...)

	// Add all referenced files (including Bazel labels) to test_files
	allTestFiles = append(allTestFiles, referencedFiles...)

	// Deduplicate and sort
	allTestFiles = deduplicateStrings(allTestFiles)
	sort.Strings(allTestFiles)

	// Set module reference
	r.SetAttr("module", ":"+moduleName)

	// Set test_files
	r.SetAttr("test_files", allTestFiles)

	// Preserve existing attributes
	if existing != nil {
		// Keep data if set
		if existing.Attr("data") != nil {
			r.SetAttr("data", existing.Attr("data"))
		}
		// Keep size if set
		if existing.Attr("size") != nil {
			r.SetAttr("size", existing.Attr("size"))
		}
		// Keep tags if set
		if existing.Attr("tags") != nil {
			r.SetAttr("tags", existing.Attr("tags"))
		}
		// Keep visibility if set
		if existing.Attr("visibility") != nil {
			r.SetAttr("visibility", existing.Attr("visibility"))
		}
	}

	return r
}

// Fix repairs incorrect rules by replacing glob expressions with explicit file lists.
func (l *terraformLang) Fix(c *config.Config, f *rule.File) {
	cfg := getConfig(c)
	if !cfg.enabled {
		return
	}

	// Get the directory path from the file
	dir := filepath.Join(c.RepoRoot, f.Pkg)

	// Collect actual files in the directory
	var tfFiles, templateFiles []string
	var hasReadme bool

	entries, err := os.ReadDir(dir)
	if err != nil {
		return
	}

	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		switch {
		case strings.HasSuffix(name, ".tf") && !strings.HasSuffix(name, ".tftest.hcl"):
			tfFiles = append(tfFiles, name)
		case strings.HasSuffix(name, ".tmpl") || strings.HasSuffix(name, ".tpl") || strings.HasSuffix(name, ".tftpl"):
			templateFiles = append(templateFiles, name)
		case name == "README.md":
			hasReadme = true
		}
	}

	// Fix each tf_module rule
	for _, r := range f.Rules {
		if r.Kind() != tfModuleKind {
			continue
		}

		// Check if srcs contains a glob (AttrStrings returns nil for non-list expressions)
		if r.Attr("srcs") != nil && r.AttrStrings("srcs") == nil {
			// srcs is not a simple string list (likely a glob), replace it
			sort.Strings(tfFiles)
			sort.Strings(templateFiles)

			srcs := make([]string, 0, len(tfFiles)+len(templateFiles)+1)
			srcs = append(srcs, tfFiles...)
			srcs = append(srcs, templateFiles...)
			if hasReadme {
				srcs = append(srcs, "README.md")
			}
			sort.Strings(srcs)
			r.SetAttr("srcs", srcs)
		}
	}
}

// Imports returns the imports for dependency resolution.
func (l *terraformLang) Imports(c *config.Config, r *rule.Rule, f *rule.File) []resolve.ImportSpec {
	return nil
}

// Embeds returns the labels for embedded dependencies.
func (l *terraformLang) Embeds(r *rule.Rule, from label.Label) []label.Label {
	return nil
}

// Resolve resolves dependencies.
func (l *terraformLang) Resolve(c *config.Config, ix *resolve.RuleIndex, rc *repo.RemoteCache, r *rule.Rule, imports interface{}, from label.Label) {
}

// getConfig retrieves the terraform configuration from the config.
func getConfig(c *config.Config) *terraformConfig {
	if raw := c.Exts[terraformName]; raw != nil {
		return raw.(*terraformConfig)
	}
	return newTerraformConfig()
}

// extractProvidersFromTerraformTf extracts provider requirements from terraform.tf.
func extractProvidersFromTerraformTf(path string, cfg *terraformConfig) []string {
	content, err := os.ReadFile(path)
	if err != nil {
		return nil
	}

	// Simple parsing: look for required_providers block
	// This is a simplified parser - in production, use HCL parser
	providers := []string{}
	lines := strings.Split(string(content), "\n")
	inRequiredProviders := false

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		if strings.Contains(trimmed, "required_providers") {
			inRequiredProviders = true
			continue
		}

		if inRequiredProviders {
			if trimmed == "}" {
				break
			}
			// Look for provider name = { pattern
			if strings.Contains(trimmed, "=") && strings.Contains(trimmed, "{") {
				parts := strings.Split(trimmed, "=")
				if len(parts) >= 1 {
					providerName := strings.TrimSpace(parts[0])
					// Check if we have a mapping
					if label, ok := cfg.providerMapping[providerName]; ok {
						providers = append(providers, label)
					}
				}
			}
		}
	}

	return providers
}

// fileFuncRegex matches Terraform file-related function calls.
// Captures the first string argument (the file path).
var fileFuncRegex = regexp.MustCompile(`(?:templatefile|file|fileset|fileexists|filebase64|filesha256|filesha512|filemd5)\s*\(\s*"([^"]+)"`)

// isBazelLabel returns true if the path is a Bazel label.
func isBazelLabel(path string) bool {
	return strings.HasPrefix(path, "//") || strings.HasPrefix(path, "@")
}

// normalizeFilePath processes a file path from a Terraform function call.
// Strips ${path.module}/ prefix, returns Bazel labels as-is,
// returns empty string for complex expressions with variables.
func normalizeFilePath(path string) string {
	// Bazel labels - return as-is
	if isBazelLabel(path) {
		return path
	}

	// Skip complex expressions containing variables like ${var.foo} or ${local.foo}
	// But allow ${path.module}
	if strings.Contains(path, "${") && !strings.HasPrefix(path, "${path.module}") {
		return ""
	}

	// Strip ${path.module}/ prefix
	path = strings.TrimPrefix(path, "${path.module}/")

	// Skip if still contains interpolation (complex expression)
	if strings.Contains(path, "${") {
		return ""
	}

	// Skip absolute paths
	if strings.HasPrefix(path, "/") {
		return ""
	}

	return path
}

// extractFilenameFromComplexPath attempts to extract the filename from a complex path.
// Returns the filename if found, empty string otherwise.
// e.g., "${var.config_dir}/settings.json" -> "settings.json"
func extractFilenameFromComplexPath(path string) string {
	// Must contain interpolation to be complex
	if !strings.Contains(path, "${") {
		return ""
	}

	// Skip Bazel labels
	if isBazelLabel(path) {
		return ""
	}

	// Find the last path component after the last /
	lastSlash := strings.LastIndex(path, "/")
	if lastSlash == -1 {
		return ""
	}

	filename := path[lastSlash+1:]

	// Must not contain interpolation itself
	if strings.Contains(filename, "${") {
		return ""
	}

	// Must look like a filename (has an extension)
	if !strings.Contains(filename, ".") {
		return ""
	}

	return filename
}

// deduplicateStrings removes duplicate strings from a slice while preserving order.
func deduplicateStrings(input []string) []string {
	seen := make(map[string]bool)
	result := make([]string, 0, len(input))
	for _, s := range input {
		if !seen[s] {
			seen[s] = true
			result = append(result, s)
		}
	}
	return result
}

// fileReferenceResult holds extracted file references and any warnings.
type fileReferenceResult struct {
	files    []string
	warnings []string // Filenames from complex paths that may need manual addition
}

// extractFileReferencesFromContent extracts file paths from Terraform file function calls.
// Returns normalized file paths (strips ${path.module}/ prefix, preserves Bazel labels).
// Also returns warnings for complex paths where we detect a filename but can't resolve the full path.
func extractFileReferencesFromContent(content string) fileReferenceResult {
	var files []string
	var warnings []string
	seen := make(map[string]bool)
	warnSeen := make(map[string]bool)

	matches := fileFuncRegex.FindAllStringSubmatch(content, -1)
	for _, match := range matches {
		if len(match) < 2 {
			continue
		}
		path := match[1]

		// Normalize path
		normalized := normalizeFilePath(path)
		if normalized != "" {
			if !seen[normalized] {
				seen[normalized] = true
				files = append(files, normalized)
			}
			continue
		}

		// Path couldn't be normalized - check if we can extract a filename for warning
		filename := extractFilenameFromComplexPath(path)
		if filename != "" && !warnSeen[filename] {
			warnSeen[filename] = true
			warnings = append(warnings, filename)
		}
	}

	sort.Strings(files)
	sort.Strings(warnings)
	return fileReferenceResult{files: files, warnings: warnings}
}

// extractFileReferencesFromTfFiles extracts file references from .tf files.
// Returns files that can be automatically added and warnings for files that need manual addition.
func extractFileReferencesFromTfFiles(dir string, tfFiles []string) fileReferenceResult {
	var allFiles []string
	var allWarnings []string
	seen := make(map[string]bool)
	warnSeen := make(map[string]bool)

	for _, tfFile := range tfFiles {
		path := filepath.Join(dir, tfFile)
		content, err := os.ReadFile(path)
		if err != nil {
			continue
		}

		result := extractFileReferencesFromContent(string(content))
		for _, f := range result.files {
			if !seen[f] {
				seen[f] = true
				allFiles = append(allFiles, f)
			}
		}
		for _, w := range result.warnings {
			if !warnSeen[w] {
				warnSeen[w] = true
				allWarnings = append(allWarnings, w)
			}
		}
	}

	sort.Strings(allFiles)
	sort.Strings(allWarnings)
	return fileReferenceResult{files: allFiles, warnings: allWarnings}
}

// extractFileReferencesFromTestFiles extracts file references from test files.
// Returns files that can be automatically added and warnings for files that need manual addition.
func extractFileReferencesFromTestFiles(dir string, testFiles []string) fileReferenceResult {
	var allFiles []string
	var allWarnings []string
	seen := make(map[string]bool)
	warnSeen := make(map[string]bool)

	for _, testFile := range testFiles {
		path := filepath.Join(dir, testFile)
		content, err := os.ReadFile(path)
		if err != nil {
			continue
		}

		result := extractFileReferencesFromContent(string(content))
		for _, f := range result.files {
			if !seen[f] {
				seen[f] = true
				allFiles = append(allFiles, f)
			}
		}
		for _, w := range result.warnings {
			if !warnSeen[w] {
				warnSeen[w] = true
				allWarnings = append(allWarnings, w)
			}
		}
	}

	sort.Strings(allFiles)
	sort.Strings(allWarnings)
	return fileReferenceResult{files: allFiles, warnings: allWarnings}
}

// extractModulesFromTfFiles extracts relative module references from .tf files.
// It looks for module blocks with source attributes pointing to relative paths.
func extractModulesFromTfFiles(dir string, tfFiles []string, currentPackage string) []string {
	var modules []string
	seen := make(map[string]bool)

	// Regex to match source = "..." in module blocks
	// This is a simplified parser - matches any source attribute
	sourceRegex := regexp.MustCompile(`source\s*=\s*"([^"]+)"`)

	for _, tfFile := range tfFiles {
		path := filepath.Join(dir, tfFile)
		content, err := os.ReadFile(path)
		if err != nil {
			continue
		}

		matches := sourceRegex.FindAllStringSubmatch(string(content), -1)
		for _, match := range matches {
			if len(match) < 2 {
				continue
			}
			source := match[1]

			// Only process relative paths (starting with ./ or ../)
			if !strings.HasPrefix(source, "./") && !strings.HasPrefix(source, "../") {
				continue
			}

			// Skip if it looks like a remote module
			if isRemoteModuleSource(source) {
				continue
			}

			label := resolveModuleSourceToLabel(source, currentPackage)
			if label != "" && !seen[label] {
				seen[label] = true
				modules = append(modules, label)
			}
		}
	}

	sort.Strings(modules)
	return modules
}

// isRemoteModuleSource checks if a source looks like a remote module reference.
func isRemoteModuleSource(source string) bool {
	// Remote module patterns to filter out
	remotePatterns := []string{
		"git::",
		"hg::",
		"s3::",
		"gcs::",
		"https://",
		"http://",
		"registry.terraform.io",
	}
	for _, pattern := range remotePatterns {
		if strings.Contains(source, pattern) {
			return true
		}
	}
	// Registry modules like "hashicorp/consul/aws"
	if strings.Count(source, "/") >= 2 && !strings.HasPrefix(source, ".") {
		return true
	}
	return false
}

// resolveModuleSourceToLabel converts a relative module source to a Bazel label.
// e.g., "./modules/foo" -> "//current/package/modules/foo:tf_module"
// e.g., "../sibling" -> "//parent/sibling:tf_module"
func resolveModuleSourceToLabel(source, currentPackage string) string {
	// Handle empty package (root)
	if currentPackage == "" {
		// Remove leading ./
		source = strings.TrimPrefix(source, "./")
		if strings.HasPrefix(source, "../") {
			// Can't go above root
			return ""
		}
		return "//" + source + ":tf_module"
	}

	// Split current package into parts
	parts := strings.Split(currentPackage, "/")

	// Handle ./ prefix
	if strings.HasPrefix(source, "./") {
		source = strings.TrimPrefix(source, "./")
		finalPath := currentPackage + "/" + source
		return "//" + finalPath + ":tf_module"
	}

	// Handle ../ prefix - go up directories
	sourceParts := strings.Split(source, "/")
	for len(sourceParts) > 0 && sourceParts[0] == ".." {
		sourceParts = sourceParts[1:]
		if len(parts) > 0 {
			parts = parts[:len(parts)-1]
		}
	}

	// Combine remaining parts
	var finalPath string
	if len(parts) > 0 {
		finalPath = strings.Join(parts, "/") + "/" + strings.Join(sourceParts, "/")
	} else {
		finalPath = strings.Join(sourceParts, "/")
	}

	return "//" + finalPath + ":tf_module"
}
