"""Repository rule for creating the Terraform module registry."""

def _terraform_modules_impl(ctx):
    """Implementation of terraform_modules repository rule.

    Creates a BUILD file that references module download repositories.
    Each module/version is a separate repository created by the module extension.
    """
    # Start building the BUILD file content
    build_content = [
        'package(default_visibility = ["//visibility:public"])',
        "",
        'load("@bazel_skylib//:bzl_library.bzl", "bzl_library")',
        'load("@rules_tf2//tf2/modules/registry:module_metadata.bzl", "module_metadata")',
        "",
        "# External module targets (references to module repositories)",
        "# These reference external repositories that download modules during loading phase",
        "",
    ]

    # Parse module repositories from JSON
    module_repositories = {}
    if ctx.attr.module_repositories_json:
        module_repositories = json.decode(ctx.attr.module_repositories_json)

    # Create references to module repositories
    # module_repositories format: {alias: {source, source_type, version, repo_name}}
    for alias_name, module_info in module_repositories.items():
        repo_name = module_info.get("repo_name", "")
        if not repo_name:
            continue

        # Create an alias that points to the module repository
        build_content.extend([
            "alias(",
            '    name = "{}_files",'.format(alias_name),
            '    actual = "@{}//:module",'.format(repo_name),
            ")",
            "",
        ])

    # Create module metadata targets
    build_content.extend([
        "# Module metadata for external references",
        "# These provide TfExternalModuleInfo for integration with tf_module",
        "",
    ])

    # Create module_metadata targets from aliases
    if ctx.attr.aliases:
        for alias_name, module_spec in ctx.attr.aliases.items():
            # module_spec format: [source, source_type, version]
            if len(module_spec) >= 3:
                source = module_spec[0]
                source_type = module_spec[1]
                version = module_spec[2]

                build_content.extend([
                    "module_metadata(",
                    '    name = "{}",'.format(alias_name),
                    '    source = "{}",'.format(source),
                    '    source_type = "{}",'.format(source_type),
                    '    version = "{}",'.format(version),
                    '    files = ":{}_files",'.format(alias_name),
                    ")",
                    "",
                ])

    # Create module_aliases.bzl for macro-time lookup
    build_content.extend([
        "",
        "# Exported files",
        "exports_files([",
        '    "module_aliases.bzl",',
        '    "module_aliases.json",',
        "])",
        "",
        "# bzl_library for stardoc integration",
        "bzl_library(",
        '    name = "module_aliases_lib",',
        '    srcs = ["module_aliases.bzl"],',
        ")",
    ])

    # Write the BUILD file
    ctx.file("BUILD.bazel", "\n".join(build_content))

    # Create module_aliases.bzl file
    # Format: {"vpc_aws_5": {"source": "...", "source_type": "...", "version": "..."}}
    alias_mapping = {}
    if ctx.attr.aliases:
        for alias_name, module_spec in ctx.attr.aliases.items():
            if len(module_spec) >= 3:
                alias_mapping[alias_name] = {
                    "source": module_spec[0],
                    "source_type": module_spec[1],
                    "version": module_spec[2],
                }

    aliases_content = [
        '"""Module alias mappings for external Terraform modules."""',
        "",
        "# This file provides alias-to-module mappings for external modules",
        "# It is auto-generated by the tf_modules extension",
        "",
        "MODULE_ALIASES = " + str(alias_mapping),
        "",
    ]
    ctx.file("module_aliases.bzl", "\n".join(aliases_content))

    # Also create JSON version for tooling
    ctx.file("module_aliases.json", json.encode_indent(alias_mapping, indent = "  "))

    # Create manifest for debugging
    manifest = {
        "modules": ctx.attr.modules,
        "aliases": ctx.attr.aliases,
        "repositories": module_repositories,
    }
    ctx.file("manifest.json", json.encode_indent(manifest, indent = "  "))

terraform_modules = repository_rule(
    implementation = _terraform_modules_impl,
    attrs = {
        "modules": attr.string_list_dict(
            doc = "Map of module sources to list of versions",
            default = {},
        ),
        "aliases": attr.string_list_dict(
            doc = "Map of alias names to [source, source_type, version] lists",
            default = {},
        ),
        "module_repositories_json": attr.string(
            doc = "JSON-encoded map of module repositories: alias -> {source, source_type, version, repo_name}",
            default = "{}",
        ),
    },
    doc = """Creates the tf_module_registry repository with references to downloaded modules.

    This rule is invoked by the tf_modules module extension to create the central
    module registry that other rules can reference.

    Example:
        terraform_modules(
            name = "tf_module_registry",
            modules = {
                "terraform-aws-modules/vpc/aws": ["5.0.0", "5.1.0"],
            },
            aliases = {
                "vpc_aws_5": ["terraform-aws-modules/vpc/aws", "registry", "5.0.0"],
            },
            module_repositories_json = "...",
        )
    """,
)
